name: Snyk Infrastructure as Code
on: push
jobs:
  snyk:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk Scanning
        uses: eeveebank/github-actions-snyk@master
        with:
          type: iac
        env:
          SNYK_TOKEN: ${{ secrets.PLATFORM_SNYK_TOKEN }}
